//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.recursoshumanos.empresa/", ConfigurationName="ServicioWS.AreaWS")]
    public interface AreaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.recursoshumanos.empresa/AreaWS/insertarRequest", ReplyAction="http://services.recursoshumanos.empresa/AreaWS/insertarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebApplication.ServicioWS.insertarResponse insertar(WebApplication.ServicioWS.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.recursoshumanos.empresa/AreaWS/insertarRequest", ReplyAction="http://services.recursoshumanos.empresa/AreaWS/insertarResponse")]
        System.Threading.Tasks.Task<WebApplication.ServicioWS.insertarResponse> insertarAsync(WebApplication.ServicioWS.insertarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.recursoshumanos.empresa/AreaWS/modificarRequest", ReplyAction="http://services.recursoshumanos.empresa/AreaWS/modificarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebApplication.ServicioWS.modificarResponse modificar(WebApplication.ServicioWS.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.recursoshumanos.empresa/AreaWS/modificarRequest", ReplyAction="http://services.recursoshumanos.empresa/AreaWS/modificarResponse")]
        System.Threading.Tasks.Task<WebApplication.ServicioWS.modificarResponse> modificarAsync(WebApplication.ServicioWS.modificarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.recursoshumanos.empresa/AreaWS/eliminarRequest", ReplyAction="http://services.recursoshumanos.empresa/AreaWS/eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebApplication.ServicioWS.eliminarResponse eliminar(WebApplication.ServicioWS.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.recursoshumanos.empresa/AreaWS/eliminarRequest", ReplyAction="http://services.recursoshumanos.empresa/AreaWS/eliminarResponse")]
        System.Threading.Tasks.Task<WebApplication.ServicioWS.eliminarResponse> eliminarAsync(WebApplication.ServicioWS.eliminarRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.recursoshumanos.empresa/AreaWS/listarTodasRequest", ReplyAction="http://services.recursoshumanos.empresa/AreaWS/listarTodasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebApplication.ServicioWS.listarTodasResponse listarTodas(WebApplication.ServicioWS.listarTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.recursoshumanos.empresa/AreaWS/listarTodasRequest", ReplyAction="http://services.recursoshumanos.empresa/AreaWS/listarTodasResponse")]
        System.Threading.Tasks.Task<WebApplication.ServicioWS.listarTodasResponse> listarTodasAsync(WebApplication.ServicioWS.listarTodasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.recursoshumanos.empresa/")]
    public partial class area : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private empleado[] empleadosField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("empleados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public empleado[] empleados {
            get {
                return this.empleadosField;
            }
            set {
                this.empleadosField = value;
                this.RaisePropertyChanged("empleados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.recursoshumanos.empresa/")]
    public partial class empleado : persona {
        
        private bool activoField;
        
        private area areaField;
        
        private string cargoField;
        
        private double sueldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public area area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
                this.RaisePropertyChanged("area");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cargo {
            get {
                return this.cargoField;
            }
            set {
                this.cargoField = value;
                this.RaisePropertyChanged("cargo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double sueldo {
            get {
                return this.sueldoField;
            }
            set {
                this.sueldoField = value;
                this.RaisePropertyChanged("sueldo");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleado))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.recursoshumanos.empresa/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private ushort generoField;
        
        private int idField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ushort genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://services.recursoshumanos.empresa/", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.recursoshumanos.empresa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApplication.ServicioWS.area area;
        
        public insertarRequest() {
        }
        
        public insertarRequest(WebApplication.ServicioWS.area area) {
            this.area = area;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://services.recursoshumanos.empresa/", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.recursoshumanos.empresa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://services.recursoshumanos.empresa/", IsWrapped=true)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.recursoshumanos.empresa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApplication.ServicioWS.area area;
        
        public modificarRequest() {
        }
        
        public modificarRequest(WebApplication.ServicioWS.area area) {
            this.area = area;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://services.recursoshumanos.empresa/", IsWrapped=true)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.recursoshumanos.empresa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarResponse() {
        }
        
        public modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.recursoshumanos.empresa/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.recursoshumanos.empresa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idArea;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(int idArea) {
            this.idArea = idArea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.recursoshumanos.empresa/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.recursoshumanos.empresa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodas", WrapperNamespace="http://services.recursoshumanos.empresa/", IsWrapped=true)]
    public partial class listarTodasRequest {
        
        public listarTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasResponse", WrapperNamespace="http://services.recursoshumanos.empresa/", IsWrapped=true)]
    public partial class listarTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.recursoshumanos.empresa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApplication.ServicioWS.area[] @return;
        
        public listarTodasResponse() {
        }
        
        public listarTodasResponse(WebApplication.ServicioWS.area[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AreaWSChannel : WebApplication.ServicioWS.AreaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AreaWSClient : System.ServiceModel.ClientBase<WebApplication.ServicioWS.AreaWS>, WebApplication.ServicioWS.AreaWS {
        
        public AreaWSClient() {
        }
        
        public AreaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AreaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.ServicioWS.insertarResponse WebApplication.ServicioWS.AreaWS.insertar(WebApplication.ServicioWS.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(WebApplication.ServicioWS.area area) {
            WebApplication.ServicioWS.insertarRequest inValue = new WebApplication.ServicioWS.insertarRequest();
            inValue.area = area;
            WebApplication.ServicioWS.insertarResponse retVal = ((WebApplication.ServicioWS.AreaWS)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.ServicioWS.insertarResponse> WebApplication.ServicioWS.AreaWS.insertarAsync(WebApplication.ServicioWS.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.ServicioWS.insertarResponse> insertarAsync(WebApplication.ServicioWS.area area) {
            WebApplication.ServicioWS.insertarRequest inValue = new WebApplication.ServicioWS.insertarRequest();
            inValue.area = area;
            return ((WebApplication.ServicioWS.AreaWS)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.ServicioWS.modificarResponse WebApplication.ServicioWS.AreaWS.modificar(WebApplication.ServicioWS.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public int modificar(WebApplication.ServicioWS.area area) {
            WebApplication.ServicioWS.modificarRequest inValue = new WebApplication.ServicioWS.modificarRequest();
            inValue.area = area;
            WebApplication.ServicioWS.modificarResponse retVal = ((WebApplication.ServicioWS.AreaWS)(this)).modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.ServicioWS.modificarResponse> WebApplication.ServicioWS.AreaWS.modificarAsync(WebApplication.ServicioWS.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.ServicioWS.modificarResponse> modificarAsync(WebApplication.ServicioWS.area area) {
            WebApplication.ServicioWS.modificarRequest inValue = new WebApplication.ServicioWS.modificarRequest();
            inValue.area = area;
            return ((WebApplication.ServicioWS.AreaWS)(this)).modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.ServicioWS.eliminarResponse WebApplication.ServicioWS.AreaWS.eliminar(WebApplication.ServicioWS.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(int idArea) {
            WebApplication.ServicioWS.eliminarRequest inValue = new WebApplication.ServicioWS.eliminarRequest();
            inValue.idArea = idArea;
            WebApplication.ServicioWS.eliminarResponse retVal = ((WebApplication.ServicioWS.AreaWS)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.ServicioWS.eliminarResponse> WebApplication.ServicioWS.AreaWS.eliminarAsync(WebApplication.ServicioWS.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.ServicioWS.eliminarResponse> eliminarAsync(int idArea) {
            WebApplication.ServicioWS.eliminarRequest inValue = new WebApplication.ServicioWS.eliminarRequest();
            inValue.idArea = idArea;
            return ((WebApplication.ServicioWS.AreaWS)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.ServicioWS.listarTodasResponse WebApplication.ServicioWS.AreaWS.listarTodas(WebApplication.ServicioWS.listarTodasRequest request) {
            return base.Channel.listarTodas(request);
        }
        
        public WebApplication.ServicioWS.area[] listarTodas() {
            WebApplication.ServicioWS.listarTodasRequest inValue = new WebApplication.ServicioWS.listarTodasRequest();
            WebApplication.ServicioWS.listarTodasResponse retVal = ((WebApplication.ServicioWS.AreaWS)(this)).listarTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.ServicioWS.listarTodasResponse> WebApplication.ServicioWS.AreaWS.listarTodasAsync(WebApplication.ServicioWS.listarTodasRequest request) {
            return base.Channel.listarTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.ServicioWS.listarTodasResponse> listarTodasAsync() {
            WebApplication.ServicioWS.listarTodasRequest inValue = new WebApplication.ServicioWS.listarTodasRequest();
            return ((WebApplication.ServicioWS.AreaWS)(this)).listarTodasAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.recursoshumanos.empresa/", ConfigurationName="ServicioWS.EmpleadoWS")]
    public interface EmpleadoWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.recursoshumanos.empresa/EmpleadoWS/listarTodosRequest", ReplyAction="http://services.recursoshumanos.empresa/EmpleadoWS/listarTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WebApplication.ServicioWS.listarTodosResponse listarTodos(WebApplication.ServicioWS.listarTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.recursoshumanos.empresa/EmpleadoWS/listarTodosRequest", ReplyAction="http://services.recursoshumanos.empresa/EmpleadoWS/listarTodosResponse")]
        System.Threading.Tasks.Task<WebApplication.ServicioWS.listarTodosResponse> listarTodosAsync(WebApplication.ServicioWS.listarTodosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodos", WrapperNamespace="http://services.recursoshumanos.empresa/", IsWrapped=true)]
    public partial class listarTodosRequest {
        
        public listarTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosResponse", WrapperNamespace="http://services.recursoshumanos.empresa/", IsWrapped=true)]
    public partial class listarTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.recursoshumanos.empresa/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WebApplication.ServicioWS.empleado[] @return;
        
        public listarTodosResponse() {
        }
        
        public listarTodosResponse(WebApplication.ServicioWS.empleado[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpleadoWSChannel : WebApplication.ServicioWS.EmpleadoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadoWSClient : System.ServiceModel.ClientBase<WebApplication.ServicioWS.EmpleadoWS>, WebApplication.ServicioWS.EmpleadoWS {
        
        public EmpleadoWSClient() {
        }
        
        public EmpleadoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication.ServicioWS.listarTodosResponse WebApplication.ServicioWS.EmpleadoWS.listarTodos(WebApplication.ServicioWS.listarTodosRequest request) {
            return base.Channel.listarTodos(request);
        }
        
        public WebApplication.ServicioWS.empleado[] listarTodos() {
            WebApplication.ServicioWS.listarTodosRequest inValue = new WebApplication.ServicioWS.listarTodosRequest();
            WebApplication.ServicioWS.listarTodosResponse retVal = ((WebApplication.ServicioWS.EmpleadoWS)(this)).listarTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication.ServicioWS.listarTodosResponse> WebApplication.ServicioWS.EmpleadoWS.listarTodosAsync(WebApplication.ServicioWS.listarTodosRequest request) {
            return base.Channel.listarTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication.ServicioWS.listarTodosResponse> listarTodosAsync() {
            WebApplication.ServicioWS.listarTodosRequest inValue = new WebApplication.ServicioWS.listarTodosRequest();
            return ((WebApplication.ServicioWS.EmpleadoWS)(this)).listarTodosAsync(inValue);
        }
    }
}
