//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.empresa/", ConfigurationName="ServicioWS.PrimerWebService")]
    public interface PrimerWebService {
        
        // CODEGEN: Generating message contract since element name name from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.empresa/PrimerWebService/helloRequest", ReplyAction="http://services.empresa/PrimerWebService/helloResponse")]
        Cliente.ServicioWS.helloResponse hello(Cliente.ServicioWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.empresa/PrimerWebService/helloRequest", ReplyAction="http://services.empresa/PrimerWebService/helloResponse")]
        System.Threading.Tasks.Task<Cliente.ServicioWS.helloResponse> helloAsync(Cliente.ServicioWS.helloRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.empresa/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.empresa/PrimerWebService/sumarRequest", ReplyAction="http://services.empresa/PrimerWebService/sumarResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.ServicioWS.sumarResponse sumar(Cliente.ServicioWS.sumarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.empresa/PrimerWebService/sumarRequest", ReplyAction="http://services.empresa/PrimerWebService/sumarResponse")]
        System.Threading.Tasks.Task<Cliente.ServicioWS.sumarResponse> sumarAsync(Cliente.ServicioWS.sumarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://services.empresa/", Order=0)]
        public Cliente.ServicioWS.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(Cliente.ServicioWS.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://services.empresa/", Order=0)]
        public Cliente.ServicioWS.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(Cliente.ServicioWS.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumar", WrapperNamespace="http://services.empresa/", IsWrapped=true)]
    public partial class sumarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int b;
        
        public sumarRequest() {
        }
        
        public sumarRequest(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sumarResponse", WrapperNamespace="http://services.empresa/", IsWrapped=true)]
    public partial class sumarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public sumarResponse() {
        }
        
        public sumarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrimerWebServiceChannel : Cliente.ServicioWS.PrimerWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrimerWebServiceClient : System.ServiceModel.ClientBase<Cliente.ServicioWS.PrimerWebService>, Cliente.ServicioWS.PrimerWebService {
        
        public PrimerWebServiceClient() {
        }
        
        public PrimerWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrimerWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimerWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrimerWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.ServicioWS.helloResponse Cliente.ServicioWS.PrimerWebService.hello(Cliente.ServicioWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            Cliente.ServicioWS.helloRequest inValue = new Cliente.ServicioWS.helloRequest();
            inValue.Body = new Cliente.ServicioWS.helloRequestBody();
            inValue.Body.name = name;
            Cliente.ServicioWS.helloResponse retVal = ((Cliente.ServicioWS.PrimerWebService)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.ServicioWS.helloResponse> Cliente.ServicioWS.PrimerWebService.helloAsync(Cliente.ServicioWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServicioWS.helloResponse> helloAsync(string name) {
            Cliente.ServicioWS.helloRequest inValue = new Cliente.ServicioWS.helloRequest();
            inValue.Body = new Cliente.ServicioWS.helloRequestBody();
            inValue.Body.name = name;
            return ((Cliente.ServicioWS.PrimerWebService)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.ServicioWS.sumarResponse Cliente.ServicioWS.PrimerWebService.sumar(Cliente.ServicioWS.sumarRequest request) {
            return base.Channel.sumar(request);
        }
        
        public int sumar(int a, int b) {
            Cliente.ServicioWS.sumarRequest inValue = new Cliente.ServicioWS.sumarRequest();
            inValue.a = a;
            inValue.b = b;
            Cliente.ServicioWS.sumarResponse retVal = ((Cliente.ServicioWS.PrimerWebService)(this)).sumar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.ServicioWS.sumarResponse> Cliente.ServicioWS.PrimerWebService.sumarAsync(Cliente.ServicioWS.sumarRequest request) {
            return base.Channel.sumarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.ServicioWS.sumarResponse> sumarAsync(int a, int b) {
            Cliente.ServicioWS.sumarRequest inValue = new Cliente.ServicioWS.sumarRequest();
            inValue.a = a;
            inValue.b = b;
            return ((Cliente.ServicioWS.PrimerWebService)(this)).sumarAsync(inValue);
        }
    }
}
